oM=new makeCM("oM");
oM.resizeCheck=1;
oM.rows=1;
oM.onlineRoot="";
oM.pxBetween=0;
oM.fillImg="cm_fill.gif";
oM.fromTop=10;
oM.fromLeft=155;
oM.wait=300;
oM.zIndex=400;
oM.useBar=1;
oM.barWidth="100%";
oM.barHeight="menu";
oM.barX=0;
oM.barY="menu";
oM.barClass="clBar";
oM.barBorderX=0;
oM.barBorderY=0;
oM.level[0]=new cm_makeLevel(90,21,"clT","clTover",1,1,"clB",0,"bottom",0,0,0,0,0);
oM.level[1]=new cm_makeLevel(102,22,"clS","clSover",1,1,"clB",0,"right",0,0,"menu_arrow.gif",10,10);
oM.makeMenu('m1','','Accueil','../heredis/accueil.htm');
oM.makeMenu('m2','','Individus','../individus/individus.htm');
oM.makeMenu('m7','m2','Patronymes','../individus/patronymes0.htm','',200,0);
oM.makeMenu('m8','m2','Liste des individus','../individus/listeindividus0.htm','',200,0);
oM.makeMenu('m9','m2','Fiches individuelles','../fiches/fiche0.htm','',200,0);
oM.makeMenu('m10','m2','Mon ascendance','../individus/ascendance0.htm','',200,0);
oM.makeMenu('m11','m2','Liste éclair','../individus/listeeclair0.htm','',200,0);
oM.makeMenu('m3','','Lieux','../lieux/lieux.htm');
oM.makeMenu('m18','m3','Liste des lieux','../lieux/lieux0.htm','',200,0);
oM.makeMenu('m19','m3','Patronymes par lieux','../lieux/patroparlieux0.htm','',200,0);
oM.makeMenu('m4','','Etats','../etats/etats.htm');
oM.makeMenu('m12','m4','Liste des événements','../etats/listeevenements0.htm','',200,0);
oM.makeMenu('m14','m4','Liste des médias','../etats/listemedias0.htm','',200,0);
oM.makeMenu('m17','m4','Statistiques','../etats/stats.htm','',200,0);
oM.makeMenu('m5','','Arbre 3D','../dswmedia/arbre3D.htm');
var avail="40+((cmpage.x2-45)/5)";
oM.menuPlacement=new Array(42,avail+"-11",avail+"*2-8",avail+"*3-12",avail+"*4-7");
oM.construct();
